### ISSUE TITLE
Add memcache details to settings.php

### ISSUE THREAD

**Issue by Floppy** [theodi/cuke-chef#10]
We need to add memcache settings for the Drupal site to settings.php. This means we add them to https://github.com/theodi/cuke-chef/blob/master/site-cookbooks/odi-website-deploy/templates/default/settings.php.erb

We need to do something like:

```
$conf['memcache_servers'] = array(
  'host1:port' => 'default', 
  'host2:port' => 'default', 
  'hostN:port' => 'default'
);
$conf['memcache_bins'] = array('cache' => 'default')
```

This assumes that each machine has a part of the memcache. Alternatively, we have a single shared memcache server elsewhere, and point to that for a single shared cache. This is probably simpler in terms of dropping and recreating nodes.

```
$conf['memcache_servers'] = array(
  'memcache_host_ip:port' => 'default'
);
$conf['memcache_bins'] = array('cache' => 'default')
```

The memcache host IP will have to come from a chef search.

**Comment by pikesley** [comment]
Yes, we should keep memcached on its own dedicated failboat(s), away from the HMS Drupal.

**Comment by Floppy** [comment]
We will do this when @pikesley has got the SQL chef searching sorted, as it'll be a simple tweak to that code. Lovely.

**Comment by Floppy** [comment]
Added links to relevant PRs for this issue. Currently the required chef role and recipe are only in the experimental environment.
